name: Change Slack Profile Picture

on:
  schedule:
    - cron: '0 6 * * 1-5' # 6 AM every working day

jobs:
  change-picture:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Change Slack Picture
      env:
        SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
      run: |
        pip install requests Pillow

        import random
        import requests
        import os
        from PIL import Image

        def crop_to_square(im):
            x, y = im.size
            size = min(x, y)
            left = (x - size)/2
            top = (y - size)/2
            right = (x + size)/2
            bottom = (y + size)/2
            return im.crop((left, top, right, bottom))

        # Change the directory path accordingly
        image_dir = './profile-pictures/'
        images = [os.path.join(image_dir, f) for f in os.listdir(image_dir) if os.path.isfile(os.path.join(image_dir, f))]
        image_path = random.choice(images)

        image = Image.open(image_path)
        image = crop_to_square(image)
        image_path = "/tmp/temp_image.jpg"
        image.save(image_path)

        with open(image_path, 'rb') as f:
            image_content = f.read()

        headers = {
            "Authorization": f"Bearer {os.environ['SLACK_OAUTH_TOKEN']}",
            "Content-Type": "application/json; charset=utf-8"
        }

        payload = {
            "image": image_content
        }

        response = requests.post('https://slack.com/api/users.setPhoto', headers=headers, data=payload)
        print(response.text)
